<?php
/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

namespace app\assets;

use yii\base\View;
use yii\web\AssetBundle;

/**
 * @author Qiang Xue <qiang.xue@gmail.com>
 * @since 2.0
 */
class AppAsset extends AssetBundle
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->sourcePath = "@app/web";
        $this-> css = [
        'css/site.css',
        'layout/styles/layout.css'
    ];
        $this-> js = [
        'layout/scripts/jquery.min.js',
        'layout/scripts/galleryviewthemes/jquery.easing.1.3.js',
        'layout/scripts/galleryviewthemes/jquery.timers.1.2.js',
        'layout/scripts/galleryviewthemes/jquery.galleryview.2.1.1.min.js',
        'layout/scripts/galleryviewthemes/jquery.galleryview.setup.js',
    ];
        $this->jsOptions['position']=\yii\web\View::POS_HEAD;

        /*public $depends = [
            'yii\web\YiiAsset',
            'yii\bootstrap\BootstrapAsset',
        ];*/
        /**
         * @return array
         */

    }


}
