<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Callback function was not found in {0}' => '',
    'Callback function {0} does not returns an array' => '',
    'Code key of setting' => '',
    'Create' => '',
    'Create Setting' => '',
    'Delete' => '',
    'List' => '',
    'Parent tab' => '',
    'Required if type in (select, multiselect, checkbox, radio), supported string with comma, json, callback function.' => '',
    'Select a parent tab ...' => '',
    'Select a type ...' => '',
    'Setting' => '',
    'Setting configure' => '',
    'Switch Field should have store with 2 value, and negative is first. Example: no,yes' => '',
    'This is a tab' => '',
    'Update' => '',
    'Update Setting' => '',
];
